# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: catpics
      POSTGRES_USER: ${DB_USER:-cat}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-scratch}

  web:
    build:
      context: .
    image: catpics
    ports:
      - "3000:5000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/catpics
      SPRING_DATASOURCE_USERNAME: ${DB_USER:-cat}
      SPRING_DATASOURCE_PASSWORD: ${DB_USER:-scratch}
      APP_AUTHENTICATION_SECRET: ${APP_AUTHENTICATION_SECRET:-5037723c-f5f8-49c4-b161-d29733d034ff}
    depends_on:
      - db
