version: '3.1'

services:

  web:
    build:
      context: .
    image: catpics
    ports:
      - "3000:5000"
    volumes:
        - ${CATPICS_DB_DIR:-data}:/etc/data
    environment:
      SQLITE_DB_FILE: /etc/data/pics.db
      APP_AUTHENTICATION_SECRET: ${APP_AUTHENTICATION_SECRET:-5037723c-f5f8-49c4-b161-d29733d034ff}

volumes:
  data: