# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: catpics
      POSTGRES_USER: cat
      POSTGRES_PASSWORD: scratch

  web:
    image: tomcat
    ports:
      - "3000:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/catpics
      SERVER_PORT: 8080