# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: mariadb:10.6
    restart: always
    ports:
      - "3306:3306"
    environment:
      MARIADB_DATABASE: catpics
      MARIADB_USER: ${DB_USER:-cat}
      MARIADB_PASSWORD: ${DB_PASSWORD:-scratch}
      MARIADB_ROOT_PASSWORD: root

  web:
    build:
      context: .
    image: catpics
    ports:
      - "3000:5000"
    command:
      - "-P:datasource.url=jdbc:mariadb://db:3306/catpics"
      - "-P:datasource.user=${DB_USER:-cat}"
      - "-P:datasource.password=${DB_PASSWORD:-scratch}"
      - "-P:authentication.secret=${APP_AUTHENTICATION_SECRET:-5037723c-f5f8-49c4-b161-d29733d034ff}"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/catpics
      SPRING_DATASOURCE_USERNAME: ${DB_USER:-cat}
      SPRING_DATASOURCE_PASSWORD: ${DB_USER:-scratch}
      APP_AUTHENTICATION_SECRET: ${APP_AUTHENTICATION_SECRET:-5037723c-f5f8-49c4-b161-d29733d034ff}
    depends_on:
      - db
